### ISSUE TITLE
Example Code not working correctly...

### ISSUE THREAD

**Issue by Steviey** [pablo14/genetic-algorithm-feature-selection#2]
I have run the original code of the example, and get the following output, any ideas?....

```
Parsed with column specification:
cols(
  .default = col_double(),
  id = col_integer(),
  diagnosis = col_character()
)
See spec(...) for full column specifications.
Error in { : task 36 failed - "NA not permitted in predictors"
```

**Comment by pablo14** [comment]
I've just downloaded the example, run it and it works ok. Try debugging your code to check if you have everything ok with your libraries.

**Comment by Steviey** [comment]
Turns out, wrapping the code unmodified into a function causes the error...
```
origExample<-function(){
[yourCode]
}
```
` Error in { : task 27 failed - "NA not permitted in predictors" `

Can you reproduce it- any ideas?

**Comment by pablo14** [comment]
I can't help with that... try debugging your code step by step.
